#!/bin/sh
if [ "$EUID" -ne 0 ]; then
  exec sudo -A "$0" "$@"
  exit
fi

DPID=
if [ "$(ps aux | grep -c Karabiner-VirtualHIDDevice-Daemon)" -le "1" ]; then
    echo "Starting Karabiner"
    nice -n -20 /Library/Application\ Support/org.pqrs/Karabiner-DriverKit-VirtualHIDDevice/Applications/Karabiner-VirtualHIDDevice-Daemon.app/Contents/MacOS/Karabiner-VirtualHIDDevice-Daemon &
    DPI=$!
fi

VKPID=
KPID=

handle_sigint() {
  echo "Ctrl+C detected. Performing cleanup..."
  if [ -n "$VKPID" ]; then
    echo "Killing vk agent pid $VKPID";
    kill $VKPID;
  fi
  if [ -n "$KPID" ]; then
    echo "Killing kanata pid $KPID";
    kill $KPID;
  fi
  if [ -n "$DPID" ]; then
    echo "Killing kanata pid $DPID";
    kill $DPID;
  fi
  exit 1 # Exit the script with an error code
}

# Trap the SIGINT signal (Ctrl+C) and call the handle_sigint function
trap handle_sigint INT

while true; do
    if [ -n "$VKPID" ]; then
        echo "Killing vk agent pid $VKPID";
        kill $VKPID;
    fi
    echo "kanata list"
    MD5=$(kanata -l | sed -e /Karabiner/d | sort -u | md5)
    nice -n -20 kanata -n -p 5829 $@ &
    KPID=$!

    # Wait for port 5829 to be open
    echo "Waiting for port 5829 to open...";
    while ! nc -z localhost 5829; do
        sleep 1;
    done
    echo "Port 5829 opened...";

    /opt/homebrew/Cellar/kanata-vk-agent/0.1.0/bin/kanata-vk-agent -b com.parallels.desktop.console -b com.microsoft.rdc.macos &
    VKPID=$!

    CURRENT_MD5=$(kanata -l | sed -e /Karabiner/d | sort -u | md5)
    while [ "$MD5" == "$CURRENT_MD5" ]; do
        sleep 2;
        CURRENT_MD5=$(kanata -l | sed -e /Karabiner/d | sort -u | md5)
    done;
    echo "kanata list"

    echo "MD5: $MD5"
    echo "CURRENT_MD5: $CURRENT_MD5"

    if [ -n "$KPID" ]; then
        echo "Killing kanata pid $KPID";
        kill -s 9 $KPID;
        sleep 2;
    fi

done
